version: '3'
services:
  mariadb:
    image: mariadb:10.7.3
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=123456
    networks:
      - default-net
  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - default-net
  minio:
    image: minio/minio:RELEASE.2022-03-08T22-28-51Z
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    networks:
      - default-net

networks:
  default-net:
    external:
      name: th_bridge
