server:
  port: 3000  # 修改 Spring Boot Web 端口
spring:
  profiles:
    active: @spring.active@   # 控制 Maven 环境切换
  application:
    name: examples
  config:
    # 必要！
    # https://docs.spring.io/spring-cloud-consul/docs/current/reference/html/#config-data-import
    import: optional:consul:localhost:8500
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        # 以下内容组合为 Consul KV 路径 "prefixes/name/data-key"
        # 即: "service/examples/dev"
        prefixes:
          - service
        name: ${spring.application.name}
        data-key: ${spring.profiles.active}
        format: YAML # Value 类型
      discovery:
        enabled: true
        register: true    # 注册自身到 Consul
        deregister: true  # 服务停止时取消注册
        service-name: ${spring.application.name}  # 注册到 Consul 的服务名
        health-check-path: /actuator/health   # 健康检查的接口 由 Spring Boot Actuator 提供
        heartbeat:
          enabled: true   # 开启 Consul 心跳机制
