server:
  port: 3000  # 修改 Spring Boot Web 端口
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: "123456"
    url: jdbc:mysql://localhost:3306/touhou_gamejam?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update